/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package medicamp_project;

import java.awt.Dimension;
import java.awt.Toolkit;
import java.sql.*;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;
import static javax.swing.JOptionPane.YES_OPTION;
import javax.swing.RowFilter;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableRowSorter;
import static jdk.nashorn.internal.objects.NativeString.search;
import net.proteanit.sql.DbUtils;


/**
 *
 * @author ilyes
 */
public class dataAdd extends javax.swing.JFrame {

    /**
     * Creates new form dataAdd
     */
    public dataAdd() {
        initComponents();
         //Dimension dim = Toolkit.getDefaultToolkit().getScreenSize();
        // this.setLocation(dim.width/2-this.getSize().width/2, dim.height/2-this.getSize().height/2);
         Dimension screenSize = Toolkit.getDefaultToolkit().getScreenSize();
         this.setSize(screenSize.width, screenSize.height);
         //BAR TITLE AND ICON :
         
         ImageIcon img = new ImageIcon("/medicamp_project/image used/ttle bar icon.png");
         

         this.setIconImage(img.getImage());
         
         this.setTitle("Base de données sur les donneurs de sang");
         /* DEFULT USER IMAGE */
         jLabel29.setVisible(false);
         jLabel1.setVisible(false);
         /*-------------------*/
         showData();
         jLabel35.setToolTipText( "Logiciel développé par: ilies Ouldmenouer , Contact : ilyasdzair1@gmail.com" );
       
         /* DEFULT trash IMAGE */
         /*-------------------*/
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel3 = new javax.swing.JPanel();
        jPanel5 = new javax.swing.JPanel();
        jPanel1 = new javax.swing.JPanel();
        jTextField1 = new javax.swing.JTextField();
        jTextField2 = new javax.swing.JTextField();
        jComboBox2 = new javax.swing.JComboBox<>();
        jComboBox5 = new javax.swing.JComboBox<>();
        jPanel2 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jSeparator3 = new javax.swing.JSeparator();
        jComboBox6 = new javax.swing.JComboBox<>();
        jLabel1 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jComboBox8 = new javax.swing.JComboBox<>();
        jComboBox9 = new javax.swing.JComboBox<>();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jSeparator5 = new javax.swing.JSeparator();
        jSeparator6 = new javax.swing.JSeparator();
        jSeparator7 = new javax.swing.JSeparator();
        jSeparator8 = new javax.swing.JSeparator();
        jPanel6 = new javax.swing.JPanel();
        jTextField3 = new javax.swing.JTextField();
        jTextField4 = new javax.swing.JTextField();
        jComboBox3 = new javax.swing.JComboBox<>();
        jComboBox10 = new javax.swing.JComboBox<>();
        jPanel7 = new javax.swing.JPanel();
        jLabel8 = new javax.swing.JLabel();
        jSeparator9 = new javax.swing.JSeparator();
        jLabel9 = new javax.swing.JLabel();
        jComboBox11 = new javax.swing.JComboBox<>();
        jLabel10 = new javax.swing.JLabel();
        jComboBox12 = new javax.swing.JComboBox<>();
        jComboBox13 = new javax.swing.JComboBox<>();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jSeparator10 = new javax.swing.JSeparator();
        jSeparator11 = new javax.swing.JSeparator();
        jSeparator12 = new javax.swing.JSeparator();
        jSeparator13 = new javax.swing.JSeparator();
        jSeparator14 = new javax.swing.JSeparator();
        jSeparator15 = new javax.swing.JSeparator();
        jPanel8 = new javax.swing.JPanel();
        jTextField5 = new javax.swing.JTextField();
        jTextField6 = new javax.swing.JTextField();
        jComboBox4 = new javax.swing.JComboBox<>();
        jComboBox14 = new javax.swing.JComboBox<>();
        jPanel9 = new javax.swing.JPanel();
        jLabel15 = new javax.swing.JLabel();
        jSeparator16 = new javax.swing.JSeparator();
        jLabel16 = new javax.swing.JLabel();
        jComboBox15 = new javax.swing.JComboBox<>();
        jLabel17 = new javax.swing.JLabel();
        jComboBox16 = new javax.swing.JComboBox<>();
        jComboBox17 = new javax.swing.JComboBox<>();
        jLabel18 = new javax.swing.JLabel();
        jLabel19 = new javax.swing.JLabel();
        jLabel20 = new javax.swing.JLabel();
        jLabel21 = new javax.swing.JLabel();
        jSeparator17 = new javax.swing.JSeparator();
        jSeparator18 = new javax.swing.JSeparator();
        jSeparator19 = new javax.swing.JSeparator();
        jSeparator20 = new javax.swing.JSeparator();
        jPanel10 = new javax.swing.JPanel();
        jTextField7 = new javax.swing.JTextField();
        jTextField8 = new javax.swing.JTextField();
        jComboBox18 = new javax.swing.JComboBox<>();
        jComboBox19 = new javax.swing.JComboBox<>();
        jPanel11 = new javax.swing.JPanel();
        jLabel22 = new javax.swing.JLabel();
        jSeparator21 = new javax.swing.JSeparator();
        jLabel23 = new javax.swing.JLabel();
        jComboBox20 = new javax.swing.JComboBox<>();
        jLabel24 = new javax.swing.JLabel();
        jComboBox21 = new javax.swing.JComboBox<>();
        jComboBox22 = new javax.swing.JComboBox<>();
        jLabel25 = new javax.swing.JLabel();
        jLabel26 = new javax.swing.JLabel();
        jLabel27 = new javax.swing.JLabel();
        jLabel28 = new javax.swing.JLabel();
        jSeparator22 = new javax.swing.JSeparator();
        jSeparator23 = new javax.swing.JSeparator();
        jSeparator24 = new javax.swing.JSeparator();
        jSeparator25 = new javax.swing.JSeparator();
        jSeparator26 = new javax.swing.JSeparator();
        jSeparator27 = new javax.swing.JSeparator();
        jSeparator28 = new javax.swing.JSeparator();
        jSeparator29 = new javax.swing.JSeparator();
        jLabel30 = new javax.swing.JLabel();
        jLabel29 = new javax.swing.JLabel();
        jPanel4 = new javax.swing.JPanel();
        jPanel12 = new javax.swing.JPanel();
        jLabel31 = new javax.swing.JLabel();
        jComboBox7 = new javax.swing.JComboBox<>();
        jLabel32 = new javax.swing.JLabel();
        jLabel35 = new javax.swing.JLabel();
        jPanel13 = new javax.swing.JPanel();
        jPanel14 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jLabel33 = new javax.swing.JLabel();
        jLabel34 = new javax.swing.JLabel();

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(218, 90, 81));

        jPanel1.setBackground(new java.awt.Color(44, 58, 71));
        jPanel1.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jPanel1.setForeground(new java.awt.Color(44, 58, 71));
        jPanel1.setLayout(null);

        jTextField1.setBackground(new java.awt.Color(44, 58, 71));
        jTextField1.setForeground(new java.awt.Color(255, 255, 255));
        jTextField1.setText("Entrez le numéro");
        jTextField1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(218, 90, 81)));
        jTextField1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTextField1MouseClicked(evt);
            }
        });
        jTextField1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField1ActionPerformed(evt);
            }
        });
        jPanel1.add(jTextField1);
        jTextField1.setBounds(60, 340, 160, 40);

        jTextField2.setBackground(new java.awt.Color(44, 58, 71));
        jTextField2.setForeground(new java.awt.Color(255, 255, 255));
        jTextField2.setText("Entrez le nom");
        jTextField2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(218, 90, 81)));
        jTextField2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTextField2MouseClicked(evt);
            }
        });
        jTextField2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField2ActionPerformed(evt);
            }
        });
        jPanel1.add(jTextField2);
        jTextField2.setBounds(60, 240, 160, 40);

        jComboBox2.setBackground(new java.awt.Color(218, 90, 81));
        jComboBox2.setForeground(new java.awt.Color(44, 58, 71));
        jComboBox2.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "janvier", "février", "mars", "avril", "mai", "juin", "juillet", "août", "septembre", "octobre", "novembre", "décembre" }));
        jComboBox2.setBorder(null);
        jComboBox2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBox2ActionPerformed(evt);
            }
        });
        jPanel1.add(jComboBox2);
        jComboBox2.setBounds(107, 520, 60, 30);

        jComboBox5.setBackground(new java.awt.Color(218, 90, 81));
        jComboBox5.setFont(new java.awt.Font("Tahoma", 0, 9)); // NOI18N
        jComboBox5.setForeground(new java.awt.Color(44, 58, 71));
        jComboBox5.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "2019", "2020", "2021", "2022", "2023", "2024", "2025", "2026", "2027", "2028", "2029" }));
        jComboBox5.setBorder(null);
        jComboBox5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBox5ActionPerformed(evt);
            }
        });
        jPanel1.add(jComboBox5);
        jComboBox5.setBounds(168, 520, 60, 30);

        jPanel2.setBackground(new java.awt.Color(218, 90, 81));
        jPanel2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jPanel2MouseClicked(evt);
            }
        });
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Ajouter");
        jPanel2.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(15, 5, -1, -1));
        jPanel2.add(jSeparator3, new org.netbeans.lib.awtextra.AbsoluteConstraints(-30, -10, 210, 30));

        jPanel1.add(jPanel2);
        jPanel2.setBounds(60, 600, 120, 40);

        jComboBox6.setBackground(new java.awt.Color(218, 90, 81));
        jComboBox6.setForeground(new java.awt.Color(44, 58, 71));
        jComboBox6.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "1", "2", "3", "4", "5", "6", "7", "8", "9", "10", "11", "12", "13", "14", "15", "16", "17", "18", "19", "20", "21", "22", "23", "24", "25", "26", "27", "28", "29", "30", "31" }));
        jComboBox6.setBorder(null);
        jComboBox6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBox6ActionPerformed(evt);
            }
        });
        jPanel1.add(jComboBox6);
        jComboBox6.setBounds(56, 520, 50, 30);

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/medicamp_project/image used/women.png"))); // NOI18N
        jPanel1.add(jLabel1);
        jLabel1.setBounds(62, 50, 130, 140);

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/medicamp_project/image used/logoutsmalll.png"))); // NOI18N
        jLabel3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel3MouseClicked(evt);
            }
        });
        jPanel1.add(jLabel3);
        jLabel3.setBounds(10, 10, 50, 50);

        jComboBox8.setBackground(new java.awt.Color(218, 90, 81));
        jComboBox8.setForeground(new java.awt.Color(255, 255, 255));
        jComboBox8.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Sexe", "Un homme", "Une femme" }));
        jComboBox8.setBorder(null);
        jComboBox8.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                jComboBox8ItemStateChanged(evt);
            }
        });
        jComboBox8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBox8ActionPerformed(evt);
            }
        });
        jPanel1.add(jComboBox8);
        jComboBox8.setBounds(77, 190, 80, 20);

        jComboBox9.setBackground(new java.awt.Color(218, 90, 81));
        jComboBox9.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jComboBox9.setForeground(new java.awt.Color(255, 255, 255));
        jComboBox9.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Choisir", "A positif", "A négatif", "B positif", "B négatif", "O positif", "O négatif", "AB-positif", "AB-négatif" }));
        jComboBox9.setBorder(null);
        jComboBox9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBox9ActionPerformed(evt);
            }
        });
        jPanel1.add(jComboBox9);
        jComboBox9.setBounds(60, 430, 160, 30);

        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/medicamp_project/image used/clocl.png"))); // NOI18N
        jPanel1.add(jLabel4);
        jLabel4.setBounds(20, 517, 40, 40);

        jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/medicamp_project/image used/forname.png"))); // NOI18N
        jPanel1.add(jLabel5);
        jLabel5.setBounds(20, 240, 40, 40);

        jLabel6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/medicamp_project/image used/phone.png"))); // NOI18N
        jPanel1.add(jLabel6);
        jLabel6.setBounds(20, 340, 40, 40);

        jLabel7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/medicamp_project/image used/bloodcels.png"))); // NOI18N
        jPanel1.add(jLabel7);
        jLabel7.setBounds(20, 420, 40, 50);
        jPanel1.add(jSeparator5);
        jSeparator5.setBounds(20, 220, 210, 30);
        jPanel1.add(jSeparator6);
        jSeparator6.setBounds(20, 310, 210, 30);
        jPanel1.add(jSeparator7);
        jSeparator7.setBounds(20, 400, 210, 20);
        jPanel1.add(jSeparator8);
        jSeparator8.setBounds(20, 310, 210, 30);

        jPanel6.setBackground(new java.awt.Color(44, 58, 71));
        jPanel6.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jPanel6.setForeground(new java.awt.Color(44, 58, 71));
        jPanel6.setLayout(null);

        jTextField3.setBackground(new java.awt.Color(44, 58, 71));
        jTextField3.setForeground(new java.awt.Color(255, 255, 255));
        jTextField3.setText("  phone");
        jTextField3.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(218, 90, 81)));
        jTextField3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTextField3MouseClicked(evt);
            }
        });
        jTextField3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField3ActionPerformed(evt);
            }
        });
        jPanel6.add(jTextField3);
        jTextField3.setBounds(70, 330, 160, 40);

        jTextField4.setBackground(new java.awt.Color(44, 58, 71));
        jTextField4.setForeground(new java.awt.Color(255, 255, 255));
        jTextField4.setText("  EntreLe Nom ...");
        jTextField4.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(218, 90, 81)));
        jTextField4.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTextField4MouseClicked(evt);
            }
        });
        jTextField4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField4ActionPerformed(evt);
            }
        });
        jPanel6.add(jTextField4);
        jTextField4.setBounds(70, 240, 160, 40);

        jComboBox3.setBackground(new java.awt.Color(218, 90, 81));
        jComboBox3.setForeground(new java.awt.Color(44, 58, 71));
        jComboBox3.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        jComboBox3.setBorder(null);
        jComboBox3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBox3ActionPerformed(evt);
            }
        });
        jPanel6.add(jComboBox3);
        jComboBox3.setBounds(110, 480, 30, 30);

        jComboBox10.setBackground(new java.awt.Color(218, 90, 81));
        jComboBox10.setForeground(new java.awt.Color(44, 58, 71));
        jComboBox10.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        jComboBox10.setBorder(null);
        jComboBox10.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBox10ActionPerformed(evt);
            }
        });
        jPanel6.add(jComboBox10);
        jComboBox10.setBounds(150, 480, 80, 30);

        jPanel7.setBackground(new java.awt.Color(218, 90, 81));
        jPanel7.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel8.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(255, 255, 255));
        jLabel8.setText("Add Doner");
        jPanel7.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 10, -1, -1));
        jPanel7.add(jSeparator9, new org.netbeans.lib.awtextra.AbsoluteConstraints(-30, -10, 210, 30));

        jPanel6.add(jPanel7);
        jPanel7.setBounds(60, 560, 120, 40);

        jLabel9.setIcon(new javax.swing.ImageIcon("C:\\Users\\ilyes\\Desktop\\medicampdesign\\userpng.png")); // NOI18N
        jPanel6.add(jLabel9);
        jLabel9.setBounds(50, 40, 140, 140);

        jComboBox11.setBackground(new java.awt.Color(218, 90, 81));
        jComboBox11.setForeground(new java.awt.Color(44, 58, 71));
        jComboBox11.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        jComboBox11.setBorder(null);
        jComboBox11.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBox11ActionPerformed(evt);
            }
        });
        jPanel6.add(jComboBox11);
        jComboBox11.setBounds(70, 480, 30, 30);

        jLabel10.setIcon(new javax.swing.ImageIcon("C:\\Users\\ilyes\\Desktop\\medicampdesign\\logoutsmalll.png")); // NOI18N
        jPanel6.add(jLabel10);
        jLabel10.setBounds(10, -30, 180, 140);

        jComboBox12.setBackground(new java.awt.Color(218, 90, 81));
        jComboBox12.setForeground(new java.awt.Color(255, 255, 255));
        jComboBox12.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "SEX", "F", "M", "Item 4" }));
        jComboBox12.setBorder(null);
        jComboBox12.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBox12ActionPerformed(evt);
            }
        });
        jPanel6.add(jComboBox12);
        jComboBox12.setBounds(70, 180, 80, 20);

        jComboBox13.setBackground(new java.awt.Color(218, 90, 81));
        jComboBox13.setForeground(new java.awt.Color(255, 255, 255));
        jComboBox13.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        jComboBox13.setBorder(null);
        jComboBox13.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBox13ActionPerformed(evt);
            }
        });
        jPanel6.add(jComboBox13);
        jComboBox13.setBounds(70, 410, 160, 30);

        jLabel11.setIcon(new javax.swing.ImageIcon("C:\\Users\\ilyes\\Desktop\\medicampdesign\\clocl.png")); // NOI18N
        jPanel6.add(jLabel11);
        jLabel11.setBounds(20, 480, 40, 40);

        jLabel12.setIcon(new javax.swing.ImageIcon("C:\\Users\\ilyes\\Desktop\\medicampdesign\\forname.png")); // NOI18N
        jPanel6.add(jLabel12);
        jLabel12.setBounds(20, 240, 40, 40);

        jLabel13.setIcon(new javax.swing.ImageIcon("C:\\Users\\ilyes\\Desktop\\medicampdesign\\phone.png")); // NOI18N
        jPanel6.add(jLabel13);
        jLabel13.setBounds(20, 330, 40, 40);

        jLabel14.setIcon(new javax.swing.ImageIcon("C:\\Users\\ilyes\\Desktop\\medicampdesign\\bloodcels.png")); // NOI18N
        jPanel6.add(jLabel14);
        jLabel14.setBounds(20, 410, 40, 40);
        jPanel6.add(jSeparator10);
        jSeparator10.setBounds(20, 220, 210, 30);
        jPanel6.add(jSeparator11);
        jSeparator11.setBounds(20, 310, 210, 30);
        jPanel6.add(jSeparator12);
        jSeparator12.setBounds(20, 400, 210, 30);
        jPanel6.add(jSeparator13);
        jSeparator13.setBounds(20, 310, 210, 30);

        jPanel1.add(jPanel6);
        jPanel6.setBounds(0, 0, 0, 0);
        jPanel1.add(jSeparator14);
        jSeparator14.setBounds(20, 400, 210, 20);
        jPanel1.add(jSeparator15);
        jSeparator15.setBounds(20, 490, 210, 30);

        jPanel8.setBackground(new java.awt.Color(44, 58, 71));
        jPanel8.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jPanel8.setForeground(new java.awt.Color(44, 58, 71));
        jPanel8.setLayout(null);

        jTextField5.setBackground(new java.awt.Color(44, 58, 71));
        jTextField5.setForeground(new java.awt.Color(255, 255, 255));
        jTextField5.setText("  phone");
        jTextField5.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(218, 90, 81)));
        jTextField5.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTextField5MouseClicked(evt);
            }
        });
        jTextField5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField5ActionPerformed(evt);
            }
        });
        jPanel8.add(jTextField5);
        jTextField5.setBounds(70, 330, 160, 40);

        jTextField6.setBackground(new java.awt.Color(44, 58, 71));
        jTextField6.setForeground(new java.awt.Color(255, 255, 255));
        jTextField6.setText("  EntreLe Nom ...");
        jTextField6.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(218, 90, 81)));
        jTextField6.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTextField6MouseClicked(evt);
            }
        });
        jTextField6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField6ActionPerformed(evt);
            }
        });
        jPanel8.add(jTextField6);
        jTextField6.setBounds(70, 240, 160, 40);

        jComboBox4.setBackground(new java.awt.Color(218, 90, 81));
        jComboBox4.setForeground(new java.awt.Color(44, 58, 71));
        jComboBox4.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        jComboBox4.setBorder(null);
        jComboBox4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBox4ActionPerformed(evt);
            }
        });
        jPanel8.add(jComboBox4);
        jComboBox4.setBounds(110, 480, 30, 30);

        jComboBox14.setBackground(new java.awt.Color(218, 90, 81));
        jComboBox14.setForeground(new java.awt.Color(44, 58, 71));
        jComboBox14.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        jComboBox14.setBorder(null);
        jComboBox14.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBox14ActionPerformed(evt);
            }
        });
        jPanel8.add(jComboBox14);
        jComboBox14.setBounds(150, 480, 80, 30);

        jPanel9.setBackground(new java.awt.Color(218, 90, 81));
        jPanel9.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel15.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel15.setForeground(new java.awt.Color(255, 255, 255));
        jLabel15.setText("Add Doner");
        jPanel9.add(jLabel15, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 10, -1, -1));
        jPanel9.add(jSeparator16, new org.netbeans.lib.awtextra.AbsoluteConstraints(-30, -10, 210, 30));

        jPanel8.add(jPanel9);
        jPanel9.setBounds(60, 560, 120, 40);

        jLabel16.setIcon(new javax.swing.ImageIcon("C:\\Users\\ilyes\\Desktop\\medicampdesign\\userpng.png")); // NOI18N
        jPanel8.add(jLabel16);
        jLabel16.setBounds(50, 40, 140, 140);

        jComboBox15.setBackground(new java.awt.Color(218, 90, 81));
        jComboBox15.setForeground(new java.awt.Color(44, 58, 71));
        jComboBox15.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        jComboBox15.setBorder(null);
        jComboBox15.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBox15ActionPerformed(evt);
            }
        });
        jPanel8.add(jComboBox15);
        jComboBox15.setBounds(70, 480, 30, 30);

        jLabel17.setIcon(new javax.swing.ImageIcon("C:\\Users\\ilyes\\Desktop\\medicampdesign\\logoutsmalll.png")); // NOI18N
        jPanel8.add(jLabel17);
        jLabel17.setBounds(10, -30, 180, 140);

        jComboBox16.setBackground(new java.awt.Color(218, 90, 81));
        jComboBox16.setForeground(new java.awt.Color(255, 255, 255));
        jComboBox16.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "SEX", "F", "M", "Item 4" }));
        jComboBox16.setBorder(null);
        jComboBox16.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBox16ActionPerformed(evt);
            }
        });
        jPanel8.add(jComboBox16);
        jComboBox16.setBounds(70, 180, 80, 20);

        jComboBox17.setBackground(new java.awt.Color(218, 90, 81));
        jComboBox17.setForeground(new java.awt.Color(255, 255, 255));
        jComboBox17.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        jComboBox17.setBorder(null);
        jComboBox17.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBox17ActionPerformed(evt);
            }
        });
        jPanel8.add(jComboBox17);
        jComboBox17.setBounds(70, 430, 160, 30);

        jLabel18.setIcon(new javax.swing.ImageIcon("C:\\Users\\ilyes\\Desktop\\medicampdesign\\clocl.png")); // NOI18N
        jPanel8.add(jLabel18);
        jLabel18.setBounds(20, 480, 40, 40);

        jLabel19.setIcon(new javax.swing.ImageIcon("C:\\Users\\ilyes\\Desktop\\medicampdesign\\forname.png")); // NOI18N
        jPanel8.add(jLabel19);
        jLabel19.setBounds(20, 240, 40, 40);

        jLabel20.setIcon(new javax.swing.ImageIcon("C:\\Users\\ilyes\\Desktop\\medicampdesign\\phone.png")); // NOI18N
        jPanel8.add(jLabel20);
        jLabel20.setBounds(20, 330, 40, 40);

        jLabel21.setIcon(new javax.swing.ImageIcon("C:\\Users\\ilyes\\Desktop\\medicampdesign\\bloodcels.png")); // NOI18N
        jPanel8.add(jLabel21);
        jLabel21.setBounds(20, 430, 40, 40);
        jPanel8.add(jSeparator17);
        jSeparator17.setBounds(20, 220, 210, 30);
        jPanel8.add(jSeparator18);
        jSeparator18.setBounds(20, 310, 210, 30);
        jPanel8.add(jSeparator19);
        jSeparator19.setBounds(20, 400, 210, 30);
        jPanel8.add(jSeparator20);
        jSeparator20.setBounds(20, 310, 210, 30);

        jPanel10.setBackground(new java.awt.Color(44, 58, 71));
        jPanel10.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jPanel10.setForeground(new java.awt.Color(44, 58, 71));
        jPanel10.setLayout(null);

        jTextField7.setBackground(new java.awt.Color(44, 58, 71));
        jTextField7.setForeground(new java.awt.Color(255, 255, 255));
        jTextField7.setText("  phone");
        jTextField7.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(218, 90, 81)));
        jTextField7.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTextField7MouseClicked(evt);
            }
        });
        jTextField7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField7ActionPerformed(evt);
            }
        });
        jPanel10.add(jTextField7);
        jTextField7.setBounds(70, 330, 160, 40);

        jTextField8.setBackground(new java.awt.Color(44, 58, 71));
        jTextField8.setForeground(new java.awt.Color(255, 255, 255));
        jTextField8.setText("  EntreLe Nom ...");
        jTextField8.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(218, 90, 81)));
        jTextField8.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTextField8MouseClicked(evt);
            }
        });
        jTextField8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField8ActionPerformed(evt);
            }
        });
        jPanel10.add(jTextField8);
        jTextField8.setBounds(70, 240, 160, 40);

        jComboBox18.setBackground(new java.awt.Color(218, 90, 81));
        jComboBox18.setForeground(new java.awt.Color(44, 58, 71));
        jComboBox18.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        jComboBox18.setBorder(null);
        jComboBox18.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBox18ActionPerformed(evt);
            }
        });
        jPanel10.add(jComboBox18);
        jComboBox18.setBounds(110, 480, 30, 30);

        jComboBox19.setBackground(new java.awt.Color(218, 90, 81));
        jComboBox19.setForeground(new java.awt.Color(44, 58, 71));
        jComboBox19.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        jComboBox19.setBorder(null);
        jComboBox19.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBox19ActionPerformed(evt);
            }
        });
        jPanel10.add(jComboBox19);
        jComboBox19.setBounds(150, 480, 80, 30);

        jPanel11.setBackground(new java.awt.Color(218, 90, 81));
        jPanel11.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel22.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel22.setForeground(new java.awt.Color(255, 255, 255));
        jLabel22.setText("Add Doner");
        jPanel11.add(jLabel22, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 10, -1, -1));
        jPanel11.add(jSeparator21, new org.netbeans.lib.awtextra.AbsoluteConstraints(-30, -10, 210, 30));

        jPanel10.add(jPanel11);
        jPanel11.setBounds(60, 560, 120, 40);

        jLabel23.setIcon(new javax.swing.ImageIcon("C:\\Users\\ilyes\\Desktop\\medicampdesign\\userpng.png")); // NOI18N
        jPanel10.add(jLabel23);
        jLabel23.setBounds(50, 40, 140, 140);

        jComboBox20.setBackground(new java.awt.Color(218, 90, 81));
        jComboBox20.setForeground(new java.awt.Color(44, 58, 71));
        jComboBox20.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        jComboBox20.setBorder(null);
        jComboBox20.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBox20ActionPerformed(evt);
            }
        });
        jPanel10.add(jComboBox20);
        jComboBox20.setBounds(70, 480, 30, 30);

        jLabel24.setIcon(new javax.swing.ImageIcon("C:\\Users\\ilyes\\Desktop\\medicampdesign\\logoutsmalll.png")); // NOI18N
        jPanel10.add(jLabel24);
        jLabel24.setBounds(10, -30, 180, 140);

        jComboBox21.setBackground(new java.awt.Color(218, 90, 81));
        jComboBox21.setForeground(new java.awt.Color(255, 255, 255));
        jComboBox21.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "SEX", "F", "M", "Item 4" }));
        jComboBox21.setBorder(null);
        jComboBox21.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBox21ActionPerformed(evt);
            }
        });
        jPanel10.add(jComboBox21);
        jComboBox21.setBounds(70, 180, 80, 20);

        jComboBox22.setBackground(new java.awt.Color(218, 90, 81));
        jComboBox22.setForeground(new java.awt.Color(255, 255, 255));
        jComboBox22.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        jComboBox22.setBorder(null);
        jComboBox22.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBox22ActionPerformed(evt);
            }
        });
        jPanel10.add(jComboBox22);
        jComboBox22.setBounds(70, 410, 160, 30);

        jLabel25.setIcon(new javax.swing.ImageIcon("C:\\Users\\ilyes\\Desktop\\medicampdesign\\clocl.png")); // NOI18N
        jPanel10.add(jLabel25);
        jLabel25.setBounds(20, 480, 40, 40);

        jLabel26.setIcon(new javax.swing.ImageIcon("C:\\Users\\ilyes\\Desktop\\medicampdesign\\forname.png")); // NOI18N
        jPanel10.add(jLabel26);
        jLabel26.setBounds(20, 240, 40, 40);

        jLabel27.setIcon(new javax.swing.ImageIcon("C:\\Users\\ilyes\\Desktop\\medicampdesign\\phone.png")); // NOI18N
        jPanel10.add(jLabel27);
        jLabel27.setBounds(20, 330, 40, 40);

        jLabel28.setIcon(new javax.swing.ImageIcon("C:\\Users\\ilyes\\Desktop\\medicampdesign\\bloodcels.png")); // NOI18N
        jPanel10.add(jLabel28);
        jLabel28.setBounds(20, 410, 40, 40);
        jPanel10.add(jSeparator22);
        jSeparator22.setBounds(20, 220, 210, 30);
        jPanel10.add(jSeparator23);
        jSeparator23.setBounds(20, 310, 210, 30);
        jPanel10.add(jSeparator24);
        jSeparator24.setBounds(20, 400, 210, 30);
        jPanel10.add(jSeparator25);
        jSeparator25.setBounds(20, 310, 210, 30);

        jPanel8.add(jPanel10);
        jPanel10.setBounds(0, 0, 0, 0);
        jPanel8.add(jSeparator26);
        jSeparator26.setBounds(20, 400, 210, 30);
        jPanel8.add(jSeparator27);
        jSeparator27.setBounds(20, 490, 210, 30);

        jPanel1.add(jPanel8);
        jPanel8.setBounds(0, 0, 0, 0);
        jPanel1.add(jSeparator28);
        jSeparator28.setBounds(20, 490, 210, 30);
        jPanel1.add(jSeparator29);
        jSeparator29.setBounds(20, 580, 210, 30);

        jLabel30.setIcon(new javax.swing.ImageIcon("C:\\Users\\ilyes\\Desktop\\medicampdesign\\whooo.png")); // NOI18N
        jPanel1.add(jLabel30);
        jLabel30.setBounds(62, 50, 150, 140);

        jLabel29.setIcon(new javax.swing.ImageIcon("C:\\Users\\ilyes\\Desktop\\medicampdesign\\man.png")); // NOI18N
        jPanel1.add(jLabel29);
        jLabel29.setBounds(62, 50, 140, 140);

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 765, Short.MAX_VALUE)
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 682, Short.MAX_VALUE)
        );

        jPanel12.setBackground(new java.awt.Color(44, 58, 71));
        jPanel12.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel31.setIcon(new javax.swing.ImageIcon("C:\\Users\\ilyes\\Desktop\\medicampdesign\\search2.png")); // NOI18N
        jLabel31.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255)));
        jLabel31.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel31MouseClicked(evt);
            }
        });
        jPanel12.add(jLabel31, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 41, 60, 50));

        jComboBox7.setBackground(new java.awt.Color(218, 90, 81));
        jComboBox7.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jComboBox7.setForeground(new java.awt.Color(255, 255, 255));
        jComboBox7.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "tous", "A positif", "A négatif", "B positif", "B négatif", "O positif", "O négatif", "AB-positif", "AB-négatif" }));
        jComboBox7.setBorder(null);
        jComboBox7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBox7ActionPerformed(evt);
            }
        });
        jPanel12.add(jComboBox7, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 40, 130, 50));

        jLabel32.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel32.setForeground(new java.awt.Color(255, 255, 255));
        jLabel32.setText("Rechercher:");
        jPanel12.add(jLabel32, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 50, -1, -1));

        jLabel35.setIcon(new javax.swing.ImageIcon("C:\\Users\\ilyes\\Desktop\\medicampdesign\\infox.png")); // NOI18N
        jPanel12.add(jLabel35, new org.netbeans.lib.awtextra.AbsoluteConstraints(710, 10, -1, -1));

        javax.swing.GroupLayout jPanel13Layout = new javax.swing.GroupLayout(jPanel13);
        jPanel13.setLayout(jPanel13Layout);
        jPanel13Layout.setHorizontalGroup(
            jPanel13Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 431, Short.MAX_VALUE)
        );
        jPanel13Layout.setVerticalGroup(
            jPanel13Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 381, Short.MAX_VALUE)
        );

        jPanel14.setBackground(new java.awt.Color(44, 58, 71));

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null}
            },
            new String [] {
                "Sexe", "Nom", "téléphone", "Dernier_don", "Sang"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jTable1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTable1MouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(jTable1);

        jLabel33.setFont(new java.awt.Font("Tahoma", 0, 10)); // NOI18N
        jLabel33.setForeground(new java.awt.Color(255, 255, 255));
        jLabel33.setText("\" Tous droits réservés pour MediCamp Club Scientifique de la Faculté de Médecine de Mostaganem \" ");

        jLabel34.setIcon(new javax.swing.ImageIcon("C:\\Users\\ilyes\\Desktop\\medicampdesign\\copeyright.png")); // NOI18N

        javax.swing.GroupLayout jPanel14Layout = new javax.swing.GroupLayout(jPanel14);
        jPanel14.setLayout(jPanel14Layout);
        jPanel14Layout.setHorizontalGroup(
            jPanel14Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel14Layout.createSequentialGroup()
                .addGroup(jPanel14Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel14Layout.createSequentialGroup()
                        .addGap(35, 35, 35)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 712, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel14Layout.createSequentialGroup()
                        .addGap(149, 149, 149)
                        .addComponent(jLabel33))
                    .addGroup(jPanel14Layout.createSequentialGroup()
                        .addGap(360, 360, 360)
                        .addComponent(jLabel34)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel14Layout.setVerticalGroup(
            jPanel14Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel14Layout.createSequentialGroup()
                .addGap(60, 60, 60)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 457, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel33)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel34, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 240, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jPanel14, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel12, javax.swing.GroupLayout.DEFAULT_SIZE, 792, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 886, Short.MAX_VALUE)
                .addComponent(jPanel13, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(433, 433, 433)
                .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel13, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 752, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(5, 5, 5)
                        .addComponent(jPanel12, javax.swing.GroupLayout.PREFERRED_SIZE, 112, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jPanel14, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addGap(0, 142, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    
    
    
    
    
    
    private void jTextField1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField1ActionPerformed
        // TODO add your handling code here:
        
    }//GEN-LAST:event_jTextField1ActionPerformed

    private void jComboBox2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBox2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jComboBox2ActionPerformed

    private void jComboBox5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBox5ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jComboBox5ActionPerformed

    private void jComboBox6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBox6ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jComboBox6ActionPerformed

    private void jComboBox8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBox8ActionPerformed
        // TODO add your handling code here:
        String s="SEX";
        s = (String) jComboBox8.getSelectedItem();
        if(s.equals("Un homme"))
        {
            jLabel29.setVisible(true);
            jLabel1.setVisible(false);
            jLabel30.setVisible(false);
        }
        
        if(s.equals("Une femme"))
        {
            jLabel1.setVisible(true);
            jLabel29.setVisible(false);
            jLabel30.setVisible(false);
        }
        
        if(s.equals("Sexe"))
        {
            jLabel30.setVisible(true);
            jLabel1.setVisible(false);
            jLabel29.setVisible(false);
        }
        
    }//GEN-LAST:event_jComboBox8ActionPerformed

    private void jTextField2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField2ActionPerformed
        // TODO add your handling code here:
        
    }//GEN-LAST:event_jTextField2ActionPerformed

    private void jTextField2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTextField2MouseClicked
        // TODO add your handling code here:
        jTextField2.setText ("");
    }//GEN-LAST:event_jTextField2MouseClicked

    private void jTextField1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTextField1MouseClicked
        // TODO add your handling code here:
        jTextField1.setText ("");
    }//GEN-LAST:event_jTextField1MouseClicked

    private void jComboBox9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBox9ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jComboBox9ActionPerformed

    private void jTextField3MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTextField3MouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField3MouseClicked

    private void jTextField3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField3ActionPerformed

    private void jTextField4MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTextField4MouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField4MouseClicked

    private void jTextField4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField4ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField4ActionPerformed

    private void jComboBox3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBox3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jComboBox3ActionPerformed

    private void jComboBox10ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBox10ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jComboBox10ActionPerformed

    private void jComboBox11ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBox11ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jComboBox11ActionPerformed

    private void jComboBox12ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBox12ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jComboBox12ActionPerformed

    private void jComboBox13ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBox13ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jComboBox13ActionPerformed

    private void jTextField5MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTextField5MouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField5MouseClicked

    private void jTextField5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField5ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField5ActionPerformed

    private void jTextField6MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTextField6MouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField6MouseClicked

    private void jTextField6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField6ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField6ActionPerformed

    private void jComboBox4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBox4ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jComboBox4ActionPerformed

    private void jComboBox14ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBox14ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jComboBox14ActionPerformed

    private void jComboBox15ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBox15ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jComboBox15ActionPerformed

    private void jComboBox16ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBox16ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jComboBox16ActionPerformed

    private void jComboBox17ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBox17ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jComboBox17ActionPerformed

    private void jTextField7MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTextField7MouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField7MouseClicked

    private void jTextField7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField7ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField7ActionPerformed

    private void jTextField8MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTextField8MouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField8MouseClicked

    private void jTextField8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField8ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField8ActionPerformed

    private void jComboBox18ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBox18ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jComboBox18ActionPerformed

    private void jComboBox19ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBox19ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jComboBox19ActionPerformed

    private void jComboBox20ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBox20ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jComboBox20ActionPerformed

    private void jComboBox21ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBox21ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jComboBox21ActionPerformed

    private void jComboBox22ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBox22ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jComboBox22ActionPerformed

    private void jComboBox8ItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_jComboBox8ItemStateChanged
        // TODO add your handling code here:
       
    }//GEN-LAST:event_jComboBox8ItemStateChanged

    private void jComboBox7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBox7ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jComboBox7ActionPerformed

    private void jPanel2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanel2MouseClicked
        // TODO add your handling code here:
        
        //When button save clicked :    
        //String sex , String name, String number ,String date ,String blood
        
         String sex = jComboBox8.getSelectedItem().toString();
         String name = jTextField2.getText();
         String number = jTextField1.getText();
                
         
         
         String day = jComboBox6.getSelectedItem().toString();
         String month = jComboBox2.getSelectedItem().toString();
         String year = jComboBox5.getSelectedItem().toString();
                 
         String date = day+"/"+month+"/"+year;        
         
         String blood = jComboBox9.getSelectedItem().toString();
                         
         showData();

         //check befor adding info if they are right ! 
         if (sex.equals("Sexe") || name.equals("") || blood.equals("Choisir")|| number.equals("") || number.equals("Entrez le numéro") || name.equals("Entrez le nom")) 
         {
            JOptionPane.showMessageDialog(null, "Veuillez confirmer les informations que vous avez entrées");
                           
            showData();

         }else 
         {      
                          
            // DefaultTableModel model = (DefaultTableModel) jTable1.getModel();
             
            //model.addRow(new Object[]{sex,name,number,date,blood});
             
             JOptionPane.showMessageDialog(null, "Le donneur a été enregistré avec succès");
             //Adding data to sql table : 
             
             creatdb(sex,name,number,date,blood);
             searchfor("tous");
           //  showData();
             //clearing the boxes : 
             clearboxes () ;
                             
          //   showData();

             
              
         }
         
         searchfor("tous");
        
        
        
        
    }//GEN-LAST:event_jPanel2MouseClicked

    private void jLabel31MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel31MouseClicked
        // TODO add your handling code here:
       showData();
       String search = jComboBox7.getSelectedItem().toString();
       searchfor(search);
      			
    }//GEN-LAST:event_jLabel31MouseClicked

    private void jTable1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTable1MouseClicked
      // TODO add your handling code here:
        					 
                    
        int SelectedRowIndex = jTable1.getSelectedRow();

                    
        String name = (jTable1.getValueAt(SelectedRowIndex,1).toString());

        try{						
					       
					       
					       
           
        delet(name);
                            
					       
        }catch(Exception ex)
					       
        {
					           
            JOptionPane.showMessageDialog(null, ex);
					       
        }
        
        searchfor("tous");                

        
    }//GEN-LAST:event_jTable1MouseClicked

    private void jLabel3MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel3MouseClicked
        // TODO add your handling code here:
        //LOGOUT :
        setVisible(false);
				
	//Goto data frame 
				
	log exit = new log();
        exit.setVisible(true);
				
        
        
    }//GEN-LAST:event_jLabel3MouseClicked



    
    
    public void clearboxes () 
    {
                        
        System.out.println(" opened cleaboxes");

             //SEXE 
             jComboBox8.setSelectedIndex(0);
             //Blood 
             jComboBox9.setSelectedIndex(0);
             //date : 
             jComboBox6.setSelectedIndex(0);
             jComboBox2.setSelectedIndex(0);
             jComboBox5.setSelectedIndex(0);
             // name :
             jTextField2.setText("Entrez le nom");
             //number :
             jTextField1.setText("Entrez le numéro");
    }
    
    
    
    
    
    
    
    
    
    
    
    public void creatdb( String sex , String name, String number ,String date ,String blood) {
        Connection c = null ;
        Statement  stmt = null ;
        
        try {
            
            Class.forName("org.sqlite.JDBC");
            
            c = DriverManager.getConnection("jdbc:sqlite:DxB19.db");
            
            
            System.out.println("Database Opened...\n");
            
            stmt = c.createStatement();
            
            
            //Creating table Doners
            
            // SQL statement for creating a new table Donerstableu :
              String sql = "CREATE TABLE IF NOT EXISTS Donerstableu (\n"
                + "	Sexe text  ,\n"
                + "	Nom text NOT NULL,\n"
                + "	téléphone text NOT NULL,\n"
                + "	Dernier_don text NOT NULL,\n"      
                + "	Sang text\n"
                + ");";
            
            
            
           	
            /* Testing ISSUE : 
              
              
            String sex ,name,number , date , blood ;
            
            sex = "male";
            name =" ilyes ";
            number ="0776749201";
            date ="12/12/2012";
            blood = " o+ ";
            
            */
            //Adding The Data : 
            sql = "INSERT INTO Donerstableu (Sexe,Nom,téléphone,Dernier_don,Sang)  VALUES ('"+sex+"','"+name+"','"+number+"','"+date+"','"+blood+"')";
				
            
            
            stmt.executeUpdate(sql);
				
				
				
            stmt.close();
            
            c.close();
            System.out.println("tableu created and info added \n");
            
        }
        catch ( Exception e ) {
                        
			System.err.println( e.getClass().getName() + ": " + e.getMessage() );
			
			System.exit(0);
                        System.out.println("erro ") ;
		
		}
		
    }
    
    public void showData() 
        {
            try{
                System.out.println(" opened showData");
                String sql="select * from Donerstableu"; 
                Class.forName("org.sqlite.JDBC");

                Connection con=DriverManager.getConnection("jdbc:sqlite:DxB19.db");
                java.sql.Statement st=con.createStatement();
                ResultSet rs=st.executeQuery(sql); 
                
                jTable1.setModel(DbUtils.resultSetToTableModel(rs));
                st.close();
                con.close();  
                
                
                
            }catch (Exception e) 
            {
                JOptionPane.showMessageDialog(null,e);
            }
            
            
            
        }
    
    public void delet (String name) 
    {
                        
        System.out.println(" opened delet");

 	Connection c = null;
		
	Statement stmt = null;
        
        try 
        {
            Class.forName("org.sqlite.JDBC");
            //Testing Issue :
            
            // jdbc:sqlite::resource:package/
			
            c = DriverManager.getConnection("jdbc:sqlite:DxB19.db");
                        
            //c = DriverManager.getConnection("jdbc:sqlite:DxB19.db");

						
            stmt = c.createStatement();        
            
            int reply = JOptionPane.showConfirmDialog(null, "Voulez-vous supprimer : "+name+"\n", "supprimer?",  JOptionPane.YES_NO_OPTION);
            
            if (reply == JOptionPane.YES_OPTION)
            {
                String sql = "DELETE FROM Donerstableu WHERE Nom = '"+name+"'";		
                stmt.executeUpdate(sql);	
		
                stmt.close();
			
                c.close();
            }
                
            
        
                        
            System.out.println("Deleted Successfully!!!");
                            

        }catch (Exception e )
        {
            
        System.err.println( e.getClass().getName() + ": " + e.getMessage() );
			
	System.exit(0);
        
        }
        
                        
        searchfor("tous");

       
    }
    
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(dataAdd.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(dataAdd.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(dataAdd.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(dataAdd.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                
                new dataAdd().setVisible(true);
                
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> jComboBox10;
    private javax.swing.JComboBox<String> jComboBox11;
    private javax.swing.JComboBox<String> jComboBox12;
    private javax.swing.JComboBox<String> jComboBox13;
    private javax.swing.JComboBox<String> jComboBox14;
    private javax.swing.JComboBox<String> jComboBox15;
    private javax.swing.JComboBox<String> jComboBox16;
    private javax.swing.JComboBox<String> jComboBox17;
    private javax.swing.JComboBox<String> jComboBox18;
    private javax.swing.JComboBox<String> jComboBox19;
    private javax.swing.JComboBox<String> jComboBox2;
    private javax.swing.JComboBox<String> jComboBox20;
    private javax.swing.JComboBox<String> jComboBox21;
    private javax.swing.JComboBox<String> jComboBox22;
    private javax.swing.JComboBox<String> jComboBox3;
    private javax.swing.JComboBox<String> jComboBox4;
    private javax.swing.JComboBox<String> jComboBox5;
    private javax.swing.JComboBox<String> jComboBox6;
    private javax.swing.JComboBox<String> jComboBox7;
    private javax.swing.JComboBox<String> jComboBox8;
    private javax.swing.JComboBox<String> jComboBox9;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel26;
    private javax.swing.JLabel jLabel27;
    private javax.swing.JLabel jLabel28;
    private javax.swing.JLabel jLabel29;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel30;
    private javax.swing.JLabel jLabel31;
    private javax.swing.JLabel jLabel32;
    private javax.swing.JLabel jLabel33;
    private javax.swing.JLabel jLabel34;
    private javax.swing.JLabel jLabel35;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel10;
    private javax.swing.JPanel jPanel11;
    private javax.swing.JPanel jPanel12;
    private javax.swing.JPanel jPanel13;
    private javax.swing.JPanel jPanel14;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JPanel jPanel8;
    private javax.swing.JPanel jPanel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JSeparator jSeparator10;
    private javax.swing.JSeparator jSeparator11;
    private javax.swing.JSeparator jSeparator12;
    private javax.swing.JSeparator jSeparator13;
    private javax.swing.JSeparator jSeparator14;
    private javax.swing.JSeparator jSeparator15;
    private javax.swing.JSeparator jSeparator16;
    private javax.swing.JSeparator jSeparator17;
    private javax.swing.JSeparator jSeparator18;
    private javax.swing.JSeparator jSeparator19;
    private javax.swing.JSeparator jSeparator20;
    private javax.swing.JSeparator jSeparator21;
    private javax.swing.JSeparator jSeparator22;
    private javax.swing.JSeparator jSeparator23;
    private javax.swing.JSeparator jSeparator24;
    private javax.swing.JSeparator jSeparator25;
    private javax.swing.JSeparator jSeparator26;
    private javax.swing.JSeparator jSeparator27;
    private javax.swing.JSeparator jSeparator28;
    private javax.swing.JSeparator jSeparator29;
    private javax.swing.JSeparator jSeparator3;
    private javax.swing.JSeparator jSeparator5;
    private javax.swing.JSeparator jSeparator6;
    private javax.swing.JSeparator jSeparator7;
    private javax.swing.JSeparator jSeparator8;
    private javax.swing.JSeparator jSeparator9;
    private javax.swing.JTable jTable1;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField jTextField2;
    private javax.swing.JTextField jTextField3;
    private javax.swing.JTextField jTextField4;
    private javax.swing.JTextField jTextField5;
    private javax.swing.JTextField jTextField6;
    private javax.swing.JTextField jTextField7;
    private javax.swing.JTextField jTextField8;
    // End of variables declaration//GEN-END:variables

    private void searchfor(String search) {

         try {
           
           DefaultTableModel table = (DefaultTableModel)jTable1.getModel();
           TableRowSorter<DefaultTableModel> tr = new TableRowSorter<DefaultTableModel>(table);
           jTable1.setRowSorter(tr);
           if (search.equals("tous")) {
               showData();
           }else {
               tr.setRowFilter(RowFilter.regexFilter(search));
           }
           
           
           
           
       }catch (Exception e) 
       {
            {JOptionPane.showMessageDialog(null,e);} 
       }
	    	

    }
}
